### ISSUE TITLE
feat(backend): Implement a mock backend server 

### ISSUE THREAD

**Issue by barjin** [barjin/nswi153-crawler#6]
This may not be needed, but for easier front-end development, I'm thinking that we could create a mock backend server.

This would only serve the expected responses - mock executions / records, so that we have something to render on the web. It might even allow for deleting / updating the records, but without persisting those in a DB.

Something like:
```typescript
...
let mockExecutions = [{executionId: 1, url: "https://test.com" ...}, {executionId: 2, url: "https://example.com" ...}]

app.get('/executions', (_, res) => {
   return mockExecutions;
});

app.get('/executions/:executionId', (req, res) => {
   return mockExecutions.find(x => x.executionId === req.params.executionId);
})

app.delete('/executions/:executionId', (req, res) => {
   mockExecutions = mockExecutions.filter(x => x.executionId !== req.params.executionId);
   return { done: true }
})
```

etc.

This should be sufficiently easy once we merge the autogenerated server stub from the OpenAPI spec (see #5 )

What do you think? 
cc @viktorija-panovska  @viktoria-hurtisova

**Comment by viktorija-panovska** [comment]
This is a good idea.
